name: Integration tests

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  dummy:
    runs-on: ubuntu-latest

    steps:
    - name: output
      run: echo "Hello world"
